### ISSUE TITLE
请问exe文件在哪里下载呢？

### ISSUE THREAD

**Issue by wulihuawuqia** [codecyou/FileManager#1]
请问exe文件在哪里下载呢？

**Comment by codecyou** [comment]
> 

https://github.com/codecyou/FileManager/releases/download/3.0.0.0/filemanager.zip
这个是很早版本的了，视频裁剪功能效率会比较低，后面的更新没有上传，如果要用到视频裁剪那部分功能的话等这一两天会更新一下程序版本

**Comment by wulihuawuqia** [comment]
感谢，感谢
