### ISSUE TITLE
Unhandled exception in script.

### ISSUE THREAD

**Issue by fernvenue** [codecyou/FileManager#2]
Hi, I just got this error when I use EXE binary:

```
Traceback (most recent call last):
  File "bin\filemanager.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "bin\MainPage.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "bin\view.py", line 18, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cv2\__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: DLL load failed while importing cv2: The specified module could not be found.
```

Seems like some packaging error with the latest release?

**Comment by codecyou** [comment]
The 64 bit program was packaged with python 3.10.4 64 bit. It work normally on my computer with windows10 21H2 version.I upload a new program packaged with Python 3.8.6 32-bit.You can try it! 
And if you use the source code to package the exe by yourself, you need to modify the some code of module loading in the moviepy source code, otherwise it will conflict with pyinstaller. I have pushed the modified code.

**Comment by fernvenue** [comment]
Thanks for your reply! After that, I found out that both 3.10.4 and 3.8.6 works fine on my other devices, so I think maybe something wrong with my system. Now I figured it out, Media Feature Pack is required for this project, most of Windows version installed that pack by default, but some other version not, such as Windows LTSC N.As [Media Feature Pack for Windows 10 N (May 2021)](https://support.microsoft.com/en-us/windows/media-feature-pack-for-windows-10-n-may-2021-93363b58-1cfd-4e07-bf77-ed0ed7ebbb66) this article mentioned, I installed it, now File Manager work so great on my device :)

Before I close this issue, I think mention this requirement in README will be so great, what do you think about that?

**Comment by codecyou** [comment]
Thank you for your proposal. I will put it in the REDME document.
I've always used it myself, and may not find some imperfections. If you have other questions or suggestions in use, welcome to discuss them together！

**Comment by codecyou** [comment]
- [ ]
