### ISSUE TITLE
macOS 系统搭建好了Pycharm ，但pywin32 环境下载不下来

### ISSUE THREAD

**Issue by kakao6** [codecyou/FileManager#4]
<img width="1016" alt="截屏2022-12-06 13 59 17" src="https://user-images.githubusercontent.com/23291423/205831995-ab99d7ee-54aa-49a6-9550-dfe74e27e73b.png">

**Comment by kakao6** [comment]
<img width="784" alt="截屏2022-12-06 14 03 08" src="https://user-images.githubusercontent.com/23291423/205833023-d77e8ac2-30e3-457d-a42f-13756e05940b.png">

**Comment by codecyou** [comment]
看着是你使用的python版本太老了的原因，python2 跟python3是不兼容的，建议更换到python3.8以上版本。其实我更推荐你安装一个windows虚拟机在windows中使用，因为该程序并未在macOS下测试过，所以不知道会不会出现权限问题。

**Comment by codecyou** [comment]
你可以百度一下macOS下python环境安装，pip安装依赖包，运行python程序等等，这些资料帖子应该很多

**Comment by kakao6** [comment]
作者你好，看下这个链接对你是否有帮助。https://blog.csdn.net/sinat_41870148/article/details/105911443?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522167030837816800182140720%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=167030837816800182140720&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-105911443-null-null.142

**Comment by codecyou** [comment]
嗯  还真是，pywin32看来只能在windows上安装，刚刚去测试了一下Ubuntu上面也没有，这个模块主要是用在“计算HASH”模块中读取exe文件的版本号和“时间戳操作”模块中修改文件时间。你如果懂的话可以把这两部分使用到pywin32的相关代码注释掉就行了

**Comment by codecyou** [comment]
稍晚一些我去上传一份删掉pywin32的代码，你可以试一下，但是还是建议你装一个windows虚拟机使用，windows版本我自己使用了很长时间，bug基本都已修复，这个代码后期就没有再继续在Ubuntu上面运行过，所以不清楚会不会出现兼容性问题

**Comment by codecyou** [comment]
好了，我新建了一个FileManagerForMacOS仓库，移除了pywin32相关部分的代码，你试一下可否运行

**Comment by wsii** [comment]
windnd.hook_dropfiles()方法失效了，改成windnd.drop_files()方法了,运行环境：python310 windnd1.0.7

**Comment by wsii** [comment]
建议用 pip freeze > ./requirements.txt 命令导出当前安装的包记录

**Comment by codecyou** [comment]
requirements.txt已上传，我用的是python3.10.4 windnd1.0.7
