### ISSUE TITLE
超牛的软件！可否加一个功能？

### ISSUE THREAD

**Issue by ilovebody** [codecyou/FileManager#5]
实践中，给指定文件夹扫描所有视频，然后建立一个特征库。对于下次新扫描的视频，如果是新的（意思是原来没有近似重复的），则将新视频的特征码进入到数据库，建议用sqlite。
意思是，日常中，大家下载新的视频，只需要扫描新的n个视频，和原来库对比，就不需要重新扫描原来的视频。
然后列出新旧视频，让用户选择保留那个。

**Comment by ilovebody** [comment]
另外现有的视频处理方式，不太好，复制出来的话，可能用户又要重新分类回去原来目录，比较麻烦，弄个界面，左边、右边展示相似视频，然后加一个删除哪个到回收站的功能就好了。

**Comment by ilovebody** [comment]
至少，可以在导出的时候在目标目录中维持原始目录

**Comment by ilovebody** [comment]
图片，视频均可建立指纹库，首先是md5或者crc32，这代表完全重复相同，然后就是图片 视频的特征码。。。
对了，为表示对您工作的尊重，已经给star和推广给朋友了

**Comment by codecyou** [comment]
谢谢支持和建议！对于视频和图片文件计算hash值和相似度两个操作都是耗时很长的，因为文件内容一致的时候，计算得到的相似度为1，所以程序就没有去单独计算文件hash值，毕竟如果文件数太多的话计算所有文件的md5等hash值的时间也是很长的。如果需要找出一模一样的文件的话可以使用“查找重复文件”这个功能，选择文件大小一致选项（如果需要指定选中某些文件，在过滤输入框中输入需要指定的文件后缀名类型，用逗号隔开就行了），然后使用“查找重复文件（hash）”功能找出上一步导出的大小相同的文件，这样就能找出一模一样的图片和视频文件了。

**Comment by codecyou** [comment]
> 可以在导出的时候在目标目录中维持原始目录

嗯，使用“搜索文件或目录”功能，时可以选择导出到指定目录、导出到单级目录并附带原目录结构、保持原目录结构的选项。
其他的功能模块导出文件默认是“导出到单级目录并附带原目录结构”，目的是为了方便操作文件，导出的时候会写出一个new_old_record记录文件的，你看一下程序界面，当对导出的文件执行完操作后复制这个new_old_record文件路径到“还原文件”功能里的输入框中，然后点击还原就可以了，程序会将导出的文件，还原回它原始的目录路径

**Comment by codecyou** [comment]
> 另外现有的视频处理方式，不太好，复制出来的话，可能用户又要重新分类回去原来目录，比较麻烦，弄个界面，左边、右边展示相似视频，然后加一个删除哪个到回收站的功能就好了。

有两种方式：
1.程序界面左小角有一个“还原文件”的按钮，当对导出的视频文件操作完成后，点击该按钮，即可自动将导出目录剩余的视频或者图片文件还原回原始目录，不需要手动操作。
2.执行文件导出操作后，程序文本框会记录一个new_old_record文件路径，该文件记录的是导出文件的原始路径信息。复制该路径到“还原文件”功能界面，输入到输入框，然后点击“还原”按钮即可自动还原导出的文件到原始目录。
如果程序界面关闭了，或者没记录该new_old_record文件路径，可以到日志中查找，在程序目录下的log目录下的operate.log中会记录所有操作以及操作记录的记录文件。也可以从“设置”界面的日志按钮中进入。

**Comment by codecyou** [comment]
> 实践中，给指定文件夹扫描所有视频，然后建立一个特征库。对于下次新扫描的视频，如果是新的（意思是原来没有近似重复的），则将新视频的特征码进入到数据库，建议用sqlite。 意思是，日常中，大家下载新的视频，只需要扫描新的n个视频，和原来库对比，就不需要重新扫描原来的视频。 然后列出新旧视频，让用户选择保留那个。

这是一个很好的建议，其实程序很早的版本有记录图片特征码的功能选项，当时使用json文件记录，但是由于可能出现外设硬盘盘符会有变动或者视频原文件目录变动导致记录的视频绝对路径和现在的视频绝对路径不一致的可能，于是后来删除的该功能选项，其实如果有记录文件的话后面再执行相似度比较，就不用再特地计算一次，可以节省很大的工作量。
但是之前考虑到可能会因为视频目录变更导致记录和现有文件绝对路径对不上，以及只记录视频名而不记录原路径可能会导致的出现大量重名文件的问题，感觉代码处理逻辑会比较混乱，故移除了这个功能，我权衡一下，到时候下次把这个选项加上。有这个选项确实会节约大量时间。
