### ISSUE TITLE
GUI窗口显示问题

### ISSUE THREAD

**Issue by ACE220284Luffy** [codecyou/FileManager#6]
win10，Python 3.10.6，1920x1080
![image](https://github.com/codecyou/FileManager/assets/87253240/69586825-87b0-47a6-a881-abfe2e5e6c98)

**Comment by codecyou** [comment]
是直接运行的源码么？
我这边没出现过窗口显示不全的情况，你有没有修改过源码中的界面参数，比如bin下的MainPage.py的第34和35行winWidth和winHeight的值？修改这两个值会影响程序界面的大小。或者是修改过功能页面的组件布局大小？

**Comment by ACE220284Luffy** [comment]
不是源码，是exe，源码运行使用太烦了

**Comment by codecyou** [comment]
这个情况还是第一次遇见，我去试了一下在我机子不管是源码还是exe都是显示正常的，我去试了一下windows显示设置把缩放调到125% 也是正常显示的，我现在重新打包一份，你试一下看能正常显示不。

**Comment by ACE220284Luffy** [comment]
感谢感谢

**Comment by codecyou** [comment]
你试一下最新的exe 能正常显示窗口界面不？

**Comment by ACE220284Luffy** [comment]
一毛一样，有办法做成可调大小的吗

**Comment by codecyou** [comment]
嗯，那有可能是系统有点差异，我打包一份不锁定窗口大小的exe

**Comment by codecyou** [comment]
filemanager_3156_x64_unlockGUI 这个是不锁定窗口的，可以鼠标拖动边框调节界面大小

**Comment by ACE220284Luffy** [comment]
这样没有问题了

**Comment by codecyou** [comment]
嗯
