### ISSUE TITLE
这个软件帮我节省了很多时间

### ISSUE THREAD

**Issue by ImJING** [codecyou/FileManager#7]
我平时需要处理很多视频和图片，感谢大佬的工具极大程度节约了我的时间。
我主要是把网络上图片做成的视频再拆分成图片，然后再加工。
希望在视频帧截取的地方加个功能，可以按帧截取整个视频，每隔30帧或60帧截取一张图片这样，
然后图片去重那里可以加个邻近的图片去重功能，以达到能只有相邻帧画面重复才去重的功能。
可以实现的话我愿意加鸡腿
大佬幸苦，感谢大佬respect.

**Comment by codecyou** [comment]
相邻帧图像去重？
指的是上一步要求每隔30帧提取的帧图像后得到的所有图片，将每一张图片只和前后图片做相似度对比？而不再进行所有图片相似度计算？

**Comment by codecyou** [comment]
最新的exe已上传了，你去试一下
