### ISSUE TITLE
非常好软件，使我的CPU风扇疯狂旋转

### ISSUE THREAD

**Issue by mzspeedwolf** [codecyou/FileManager#9]
感恩感谢，检测视频文件损坏/不完整功能节省了大量时间。
我的疑问是在此功能运行过程中，CPU（5800x）确实是满载的，但磁盘读取只有不到50mb/s，以及并没有使用到GPU的资源（6750GRE）。
请问这是因为功能基于ffmpeg，所以GPU以及磁盘性能无法利用，还是单纯因为CPU已经瓶颈导致磁盘性能无法利用？（又或者是因为是AMD GPU？）
最后是一点建议：功能执行之后需要一个“停止”功能，以及能否显示已经执行了哪些文件。
最后再次感恩感谢！😊

**Comment by codecyou** [comment]
> 感恩感谢，检测视频文件损坏/不完整功能节省了大量时间。 我的疑问是在此功能运行过程中，CPU（5800x）确实是满载的，但磁盘读取只有不到50mb/s，以及并没有使用到GPU的资源（6750GRE）。 请问这是因为功能基于ffmpeg，所以GPU以及磁盘性能无法利用，还是单纯因为CPU已经瓶颈导致磁盘性能无法利用？（又或者是因为是AMD GPU？） 最后是一点建议：功能执行之后需要一个“停止”功能，以及能否显示已经执行了哪些文件。 最后再次感恩感谢！😊

这个功能是通过命令‘ffmpeg -v error -i video_path -f null -'来实现的，本质就是ffmpeg快速读取一遍视频文件，如果视频文件时间轴信息出错，就认为该视频不完整或者已损坏。
这个功能是因为几年前用抖音app缓存了很多无水印的原视频文件（以前的抖音app是能直接在手机目录里找到缓存的原视频文件），但是导出到电脑后发现，有很多视频没有缓存完整，就是能播放但是会看到进度条缺失一大块。用这个功能能将那些不完整和已损坏的视频文件找出来。

但是这个功能实际使用会有一些bug。比如：检查大文件时候非常慢，占用资源，而且可能会误报（本人亲测用这个功能检查网上下载的电影文件，有时候会误报视频出错，实际播放没有问题）
这个功能好几年没用过了，主要用在批量检查小视频短视频文件是否完整，这种情况下比较方便。
如果要检查长视频文件，比如几十分钟、几个小时的电影，就不好用了，特慢，结果还不一定准确，有可能会误报。
所以如果检查电影文件的话就不要用这个功能了，耗时太久。

**Comment by mzspeedwolf** [comment]
感谢解答
